from typing import Optional

class Synth:
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def setting_setnum(self, name: str, value: float) -> None: ...
    def sfload(self, filename: str) -> int: ...
    def sfont_select(self, chan: int, sfid: int) -> None: ...
