from typing import List, Optional, Union, Dict, Any

class MidiFile:
    def __init__(self) -> None: ...
    def save(self, filename: str) -> None: ...
    tracks: List["MidiTrack"]

class MidiTrack:
    def __init__(self) -> None: ...
    def append(self, message: "Message") -> None: ...

class Message:
    def __init__(self, type: str, **kwargs: Any) -> None: ...
